title: Qiyu (Yusuf) Ma's Homepage
page-top-title: Qiyu (Yusuf) Ma
top-section-bg-text: Electronic Engineering
home-subtitle: Qiyu Ma | 马琦钰
copyright-text: '&copy; Qiyu Ma 2025-2026. All Rights Reserved.'
